// <auto-generated />
using System;
using DiceSimulationProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiceSimulationProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiceSimulationProject.Models.DiceResultModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiceRollId")
                        .HasColumnType("int");

                    b.Property<int>("ResultsDie1")
                        .HasColumnType("int");

                    b.Property<int>("ResultsDie2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiceRollId");

                    b.ToTable("DiceResults");
                });

            modelBuilder.Entity("DiceSimulationProject.Models.DiceRollModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfRolls")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DiceRoll");
                });

            modelBuilder.Entity("DiceSimulationProject.Models.DiceResultModel", b =>
                {
                    b.HasOne("DiceSimulationProject.Models.DiceRollModel", "DiceRoll")
                        .WithMany("DiceResults")
                        .HasForeignKey("DiceRollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiceRoll");
                });

            modelBuilder.Entity("DiceSimulationProject.Models.DiceRollModel", b =>
                {
                    b.Navigation("DiceResults");
                });
#pragma warning restore 612, 618
        }
    }
}
